<?php
/**
 * Created by PhpStorm.
 * User: M
 * Date: 17/6/21
 * Time: 下午12:27
 */

namespace app\components\widgets;

use Yii;

class ActiveForm extends \yii\bootstrap\ActiveForm
{
    const TYPE_FORM = 1;
    const TYPE_SEARCH = 2;

    public $fieldClass = 'app\components\widgets\ActiveField';

    public $module;

    public function init()
    {
        $this->moduleConfig();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function moduleConfig()
    {
        $this->module = $this->module ? $this->module : self::TYPE_FORM;
        if($this->module === self::TYPE_FORM){
            /*$this->layout = 'horizontal';
            $this->fieldConfig = [
                'template' => '{label} <div class="row"><div class="col-sm-6">{input}</div><div class="col-sm-3">{error}</div></div>',
                'labelOptions' => ['class' => 'control-label col-sm-2']
            ];*/
        }else if($this->module === self::TYPE_SEARCH){
            $this->method = 'get';
            $this->action = Yii::$app->requestedAction->id;
            //$this->errorCssClass = false;
            //$this->successCssClass = false;
            $this->options = [
                'class' => 'form-inline'
            ];
            $this->fieldConfig = [
                'template' => '{label}{input}',
                'options' => [
                    'class' => 'form-group',
                    'style' => 'margin:5px 10px 5px 0',
                ],
            ];
        }
    }
}