<?php

namespace app\models\search;

use yii\base\Model;
use app\models\AuthItem;
use yii\helpers\ArrayHelper;
use yii\data\ActiveDataProvider;

class PermissionSearch extends AuthItem
{
    public $visible;

    /**
    * @inheritdoc
    */
    public function rules()
    {
        return [
            [['describe'], 'string', 'max' => 64],
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $this->type = self::TYPE_PERMISSION;
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function afterFind()
    {
        $this->visible = $this->menu === null ? false : true;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        return Model::scenarios();
    }

    /**
     * @param array $params
     * @return ActiveDataProvider
     */
    public function search(Array $params)
    {
        $query = self::find()->where(['type' => self::TYPE_PERMISSION])->joinWith('menu');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => ArrayHelper::getValue($params, 'per-page', 10)
            ],
        ]);

        $this->load($params);

        if(!$this->validate()) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            'describe' => $this->describe
        ]);

        return $dataProvider;
    }
}