<?php
/**
 * Created by PhpStorm.
 * User: M
 * Date: 17/10/12
 * Time: 上午10:25
 */

namespace app\controllers;

use Yii;
use app\models\Picture;
use yii\web\UploadedFile;
use app\models\OperateLog;
use app\models\search\PictureSearch;
use app\components\helpers\UploadHelper;

/**
 * 相片管理
 * Class PictureController
 * @package app\controllers
 */
class PictureController extends Controller
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        $this->operateModule = OperateLog::EVENT_MODULE_PICTURE;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     * @return string
     */
    public function actionList()
    {
        $searchModel = new PictureSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('list',[
            'searchModel'=>$searchModel,
            'dataProvider'=>$dataProvider
        ]);
    }

    /**
     * 创建
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        return $this->save();
    }

    /**
     * 更新
     * @return string|\yii\web\Response
     */
    public function actionUpdate()
    {
        return $this->save(false);
    }

    /**
     * 详情
     * @return string
     */
    public function actionView()
    {
        return $this->render('view',[
            'model' => $this->findModel()
        ]);
    }

    /**
     * 删除
     * @return \yii\web\Response
     * @throws \Exception
     * @throws \Throwable
     */
    public function actionDelete()
    {
        $model = $this->findModel();
        if($model->delete()){
            $this->operateId = $model->id;
            $this->alert(Yii::t('common','Delete Successfully'), self::ALERT_SUCCESS);
        }else{
            $this->alert(Yii::t('common','Delete Failure'));
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * 保存
     * @param bool $isCreate
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    private function save($isNewRecord = true)
    {
        $model = $isNewRecord ? new Picture() : $this->findModel();
        
        $request = Yii::$app->request;
        if($request->isPost){
            if($model->load($request->post())){
                // 传到七牛云
                $uploadedFile = UploadedFile::getInstance($model, 'picture');
                if($uploadedFile){
                    $model->picture = UploadHelper::qnUpload($uploadedFile->tempName, $uploadedFile->extension);
                }
                if($model->validate()){
                    if($model->save(false)){
                        $this->alert(Yii::t('common', $isNewRecord ? 'Create Successfully' : 'Update Successfully'), self::ALERT_SUCCESS);
                        $this->operateId = $model->id;
                        if($isNewRecord){
                            return $this->redirect('create');
                        }
                    }else{
                        $this->alert(Yii::t('common', $isNewRecord ? 'Create Failure' : 'Update Failure'));
                    }
                }
            }else{
                $this->exception(Yii::t('common', 'Illegal Operation'));
            }
        }
        return $this->render('form',[
            'model' => $model
        ]);
    }

    /**
     * 查询
     * @return  Picture the loaded model
     * @throws \yii\web\NotFoundHttpException
     */
    public function findModel()
    {
        $id = (int) Yii::$app->request->get('id', 0);
        if($id){
            if(($model = Picture::findOne($id)) !== null){
                return $model;
            }
        }
        $this->exception(Yii::t('common', 'Illegal Request'));
    }
}
