<?php
namespace app\controllers;

use Yii;
use app\models\AuthItem;
use app\models\OperateLog;
use app\models\AuthItemChild;
use app\models\search\RoleSearch;

/**
 * 角色管理
 * Class RoleController
 * @package app\controllers
 */
class RoleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        $this->operateModule = OperateLog::EVENT_MODULE_ROLE;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     * @return string
     */
    public function actionList()
    {
        $searchModel = new RoleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('list',[
            'searchModel'=>$searchModel,
            'dataProvider'=>$dataProvider
        ]);
    }

    /**
     * 创建
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        return $this->save();
    }

    /**
     * 更新
     * @return string|\yii\web\Response
     */
    public function actionUpdate()
    {
        return $this->save(false);
    }

    /**
     * 详情
     * @return string
     */
    public function actionView()
    {
        return $this->render('view',[
            'model' => $this->findModel()
        ]);
    }

    /**
     * 删除
     * @return \yii\web\Response
     * @throws \Exception
     * @throws \Throwable
     */
    public function actionDelete()
    {
        $model = $this->findModel();
        if($model->delete()){
            $this->operateId = 0;
            $this->operateDescribe = '( '. $model->name .' )';
            $this->alert(Yii::t('common','Delete Successfully'), self::ALERT_SUCCESS);
        }else{
            $this->alert(Yii::t('common','Delete Failure'));
        }
        return $this->redirect(Yii::$app->request->referrer);
    }


    /**
     * 分配权限
     * @return string
     * @throws \yii\db\Exception
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionAuth()
    {
        $model = $this->findModel();

        $request = Yii::$app->request;
        if($request->isPost){
            $postData = $request->post('checkbox');
            if($postData){
                $trans = Yii::$app->db->beginTransaction();
                try{
                    // 删除旧权限
                    AuthItemChild::deleteAll(['parent' => $model->name]);
                    // 添加新权限
                    $authItemChild = new AuthItemChild();
                    foreach ($postData as $val) {
                        $_authItemChild = clone $authItemChild;
                        $_authItemChild->parent = $model->name;
                        $_authItemChild->child = $val;
                        $_authItemChild->save(false);
                        unset($_authItemChild);
                    }
                    $trans->commit();
                    $this->alert(Yii::t('common', 'Auth Successfully'), self::ALERT_SUCCESS);
                    $this->operateId = 0;
                    $this->operateDescribe = '( '. $model->name .' )';

                }catch (\Exception $e){
                    $trans->rollBack();
                    $this->alert(Yii::t('common', 'Auth Failure'));
                }
            }else{
                $this->exception(Yii::t('common', 'Illegal Operation'));
            }
        }

        $data = AuthItemChild::getRoleData($model->name);
        return $this->render('auth', [
            'data' => $data
        ]);
    }

    /**
     * 保存
     * @param bool $isCreate
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    private function save($isNewRecord = true)
    {
        $model = $isNewRecord ? new AuthItem() : $this->findModel();
        $model->type = AuthItem::TYPE_ROLE;
        
        $request = Yii::$app->request;
        if($request->isPost){
            if($model->load($request->post()) && $model->validate()){
                if($model->save(false)){
                    $this->alert(Yii::t('common', $isNewRecord ? 'Create Successfully' : 'Update Successfully'), self::ALERT_SUCCESS);
                    $this->operateId = 0;
                    $this->operateDescribe = '( '. $model->name .' )';
                    if($isNewRecord){
                        return $this->redirect('create');
                    }
                }else{
                    $this->alert(Yii::t('common', $isNewRecord ? 'Create Failure' : 'Update Failure'));
                }
            }else{
                $this->exception(Yii::t('common', 'Illegal Operation'));
            }
        }
        return $this->render('form',[
            'model' => $model
        ]);
    }

    /**
     * 查询
     * @return  AuthItem the loaded model
     * @throws \yii\web\NotFoundHttpException
     */
    public function findModel()
    {
        $name = Yii::$app->request->get('id');
        if($name){
            if(($model = AuthItem::findOne(['name' => $name, 'type' => AuthItem::TYPE_ROLE])) !== null){
                return $model;
            }
        }
        $this->exception(Yii::t('common', 'Illegal Request'));
    }
}
