<?php
/**
 * Created by PhpStorm.
 * User: M
 * Date: 17/10/12
 * Time: 上午10:25
 */

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\OperateLog;
use app\models\search\UserSearch;

/**
 * 用户管理
 * Class UserController
 * @package app\controllers
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        $this->operateModule = OperateLog::EVENT_MODULE_USER;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     * @return string
     */
    public function actionList()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('list',[
            'searchModel'=>$searchModel,
            'dataProvider'=>$dataProvider
        ]);
    }

    /**
     * 更新
     * @return string|\yii\web\Response
     */
    public function actionUpdate()
    {
        return $this->save();
    }

    /**
     * 详情
     * @return string
     */
    public function actionView()
    {
        return $this->render('view',[
            'model' => $this->findModel()
        ]);
    }

    /**
     * 保存
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     */
    private function save()
    {
        $model = $this->findModel();

        $request = Yii::$app->request;
        if($request->isPost){
            if($model->load($request->post())){
                if($model->validate()){
                    if($model->save(false)){
                        $this->alert(Yii::t('common', 'Update Successfully'), self::ALERT_SUCCESS);
                        $this->operateId = $model->id;
                    }else{
                        $this->alert(Yii::t('common', 'Update Failure'));
                    }
                }
            }else{
                $this->exception(Yii::t('common', 'Illegal Operation'));
            }
        }
        return $this->render('form',[
            'model' => $model
        ]);
    }

    /**
     * 查询
     * @return  User the loaded model
     * @throws \yii\web\NotFoundHttpException
     */
    public function findModel()
    {
        $id = (int) Yii::$app->request->get('id', 0);
        if($id){
            if(($model = User::findOne($id)) !== null){
                return $model;
            }
        }
        $this->exception(Yii::t('common', 'Illegal Request'));
    }
}
