<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%album}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $cover
 * @property integer $created_at
 */
class Album extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%album}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $required = ['name'];
        if($this->isNewRecord){
            $required[] = 'cover';
        }
        return [
            [$required, 'required'],
            [['created_at'], 'integer'],
            [['name'], 'string', 'max' => 10],
            [['cover'], 'image', 'maxFiles' => 1, 'extensions' => 'jpg, jpeg, gif, png', 'wrongExtension' => '图片格式只能为{extensions}', 'maxSize' => 10*1024*1024, 'tooBig' => '图片大小不能超过10M'],
            [['name'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '名称',
            'cover' => '封面',
            'created_at' => '创建时间',
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->created_at = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * 相册
     * @return array
     */
    public static function albumArray()
    {
        return self::find()->select('name')->indexBy('id')->asArray()->column();
    }
}
